name: Node.js CD

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v22
      uses: actions/setup-node@v3
      with:
        node-version: "22.x"
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/"
