name: Node.js CD

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v22
      uses: actions/setup-node@v3
      with:
        node-version: "22.x"
        cache: 'npm'
    - run: npm run build --if-present
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/
        tag: ${{ github.ref }}