name: Node.js CI

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v22
      uses: actions/setup-node@v3
      with:
        node-version: "22.x"
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: tar -zcvf release.tar.gz dist/
    - uses: actions/upload-artifact@v4
      with:
        path: release.tar.gz
